BOOTSTRAP;
Es un framewok de ccs y html con algunos componentes de javascrip
tiene un extenso prediseños de componentes y los mas importante es que es responsive.
puede usarse: con el cdn (son los link que dan en la pagina o se puede descargar en la libreria de BOOTSTRAP)

#layout (diseño)
container, es el  diseño basico, son necesarios para diseñar el sistema de cuadricula.
tallas container ( sm, md, lg, xl)
IMPORTANTE; la definicion de la clase de bootstrap va dentro de class, dentro de la etiqueta.

